---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_facts["distribution"] == "Ubuntu"

  - name: install httpd and php package for RedHat
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: true
    when: ansible_facts["distribution"] == "RedHat"
