---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_facts["distribution"] == "RedHat"

  - name: install updates (Ubuntu)
    tags: always    
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_facts["distribution"] == "Ubuntu"

