- name: install httpd package (RedHat)
  tags: redhat,apache,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible['distribution'] == "RedHat"

- name: start and enable httpd (RedHat)
  tags: redhat,apache,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible['distribution'] == "RedHat"


